name: 'Hello Move - Schneller, einfacher den Umzug buchen'
favicon: null
layout_spectrum: 0.704559575766325
typography_spectrum: 0.4618568504229188
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6368189530912787
  lightness: 0.5634342858102173
  saturation: 0.7483114555943757
  rhythmicContrast: 0.9576430516317487
purpose: []
