name: 'Hello Move - Schneller, einfacher den Umzug buchen'
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040402'
    - '#d6dacb'
    - '#969787'
    - '#797762'
    - '#3b3c33'
  brandStrength: 0.75
  lightness: 0.5634342858102173
  saturation: 0.7483114555943757
  rhythmicContrast: 0.9576430516317487
purpose: []
